### PR TITLE
Add rpi2 and rpi3 targets

### PR DESCRIPTION
**Pull request by irgendwie**
- Includes dma patch by tomga (https://github.com/tomga/genode/commit/61abaa60eb18c8cd89a030b522f54c943d438b50)

Currently I don't find the time to incorporate the two platforms in a cleaner way,
so a lot of redundant code can be found in this patch.

### CODE REVIEW

**Comment by privatereese** [comment]
@BugUser0815 please check with @irgendwie  if you find Problems in the code for the raspberry pi 1.
If you don't find any you have my go to merge or tell me to merge.
Code works for my use case scenario for the raspberry pi 2 and 3 clusters.
We might want to adjust the dom0-HW file in the respective repository here: https://github.com/argos-research/genode-dom0-HW/pull/13
Impirically working ram-quota should be **below 347M** for **task loader component**.

**Comment by irgendwie** [comment]
I change the build process to only add the bugfix by tomga if the platform is a RPi 2 or 3.
The RPi 1 doesn't work anymore when using the bugfix.
That way the PR should be safe to merge @privatereese and @BugUser0815

**Comment by privatereese** [comment]
Looks ok to me, however I couldn't test it. Would merge if you also gave your ok @BugUser0815 .

**Comment by irgendwie** [comment]
@privatereese due to changes in the kernel a merge of https://github.com/irgendwie/foc/tree/malsami-rpi23 is needed beforehand
RAM is limited to 992 MB for both RPi2 and RPi3

**Comment by privatereese** [comment]
@irgendwie I tested it on friday and I am ok with the fixes, will merge it if @BugUser0815 is also fine with it.

**Review by privatereese — APPROVED** [review]

**Pull request merged**
